---
- name: Reload systemd
  systemd:
    daemon_reload: true
    state: restarted

- name: Reload Firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  become: true

- name: Teleport Service
  systemd:
    name: teleport
    state: restarted
    enabled: true
  become: true